Crncc 1717
PA-NIHR-CRN/dte pull request #101
Opened 2024-01-03 13:14 UTC by ThomasJackSmolen

In the ManualEntry.tsx file
 - removed the (optional) part of the postcode label
 - added a required field in the rules with an error message to alert user to enter a postcode

2024-01-17 14:31 UTC, paddyduff31 requested changes
- Remove unnecessary comments

2024-01-25 11:43 UTC, kevinofficer requested changes

2024-01-25 11:43 UTC, kevinofficer commented on src/components/Shared/FormElements/AddressFormComponents/ManualEntry.test.tsx
> +      expect(screen.getByText("Enter a real postcode")).toBeInTheDocument();
Your test expects "enter a real postcode", but your component message renders "Enter your postcode", update one of these to remain consistent with the rest of the application.

2024-01-25 11:43 UTC, kevinofficer commented on src/components/Shared/FormElements/AddressFormComponents/ManualEntry.tsx
> +            required: "Enter your postcode",
update is necessary to match the test above

2024-01-25 11:43 UTC, kevinofficer commented on src/components/Shared/FormElements/AddressFormComponents/ManualEntry.test.tsx
> +      expect(screen.getByText("Enter your postcode")).toBeInTheDocument();
is "enter your postcode" the correct validation message?

2024-01-25 11:43 UTC, kevinofficer commented on src/components/Shared/FormElements/AddressFormComponents/ManualEntry.test.tsx
> +      expect(screen.getByDisplayValue("test postcode")).toBeInTheDocument();
now that a real postcode is required, is this causing a failure? use a real postcode format 
e.g. PA London, SW1E 5DN

2024-01-25 11:43 UTC, kevinofficer commented on src/components/Shared/FormElements/AddressFormComponents/ManualEntry.test.tsx
> +        target: { value: "test postcode" },
now that a real postcode is required, is this causing a failure? use a real postcode format 
e.g. PA London, SW1E 5DN

2024-02-01 09:36 UTC, paddyduff31 commented on src/components/Shared/FormElements/AddressFormComponents/ManualEntry.tsx
> +              if (value.trim() === "") {
Can we change this back to the original implementation please?

2024-02-01 14:59 UTC, paddyduff31 approved these changes

2024-02-01 14:59 UTC, merged